### ISSUE TITLE
QTL nominal files

### ISSUE THREAD

**Issue by zhangpicb** [gandallab/Fetal_metaQTL#2]
Dear @mgandal @cjops @cyap7 @danielduyvo @leamhernandez 

Thanks for your great data!

These eQTL mapping files in https://www.synapse.org/Synapse:syn51177089 are MAF(minor allele frequency) or eaf missing! could these files will update?

Thanks in advanced!

**Comment by cindywen96** [comment]
https://drive.google.com/file/d/1LMyMhTtQ23dWFik7HI_NXuefP5fZnt7H/view?usp=drive_link

Please find the MAF files here. File was too large to upload on GitHub.
