### ISSUE TITLE
gene info missing

### ISSUE THREAD

**Issue by XiaKwan** [gandallab/Fetal_metaQTL#3]
Dear @cjops @mgandal @cyap7 @danielduyvo @leamhernandez:

Thanks for your helpful data!

It seems like the gene information of each line in the Galaxy file sQTL.mixed.40hcp.group.perm.genes.txt.gz (https://usegalaxy.org/api/datasets/f9cad7b01a472135215917481f463620/display?to_ext=tabular) is missing. How could I find that out? Or could this file be updated?

Thanks a lot!

**Comment by cindywen96** [comment]
In the first column `gene_id` there are gene ENSG ids and gene names for each intron. For example, `1:16310:16607:clu_7638_NA:ENSG00000227232.5_3:WASH7P`.

**Comment by XiaKwan** [comment]
Sorry about that. My mistake. It's the file sQTL.mixed.nominal.40hcp.allpairs.txt.gz that i'm confusing. 
The first column is like `10:100000316:100003848:clu_20610_NA`, without ENSG ids and gene names as you mentioned.

**Comment by cindywen96** [comment]
Intron annotation files are available in Synapse [https://doi.org/10.7303/syn50897018.5.](https://doi.org/10.7303/syn50897018.5)
`leafcutter_clusters_to_genes.txt` maps intron cluster to genes, or `all.introns.tested.tsv` directly maps introns to genes. These two files should be mostly consistent in terms of intron-gene mapping.
